[package]
name = "rcar"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-nrf = {version = "0.3.1", features= [
    "gpiote",
    "nfc-pins-as-gpio",
    "nrf52833",
    "time-driver-rtc1",
    "time",
    ]}
embassy-time = { version = "0.4", default-features = false, features = ["defmt-timestamp-uptime", "defmt"] }
embassy-sync = "0.6.2"
embedded-hal = "1.0"
embassy-futures = { version = "0.1", default-features = false }

embassy-executor = { version = "0.7", default-features = false, features = [
    "arch-cortex-m", 
    "defmt", 
    "executor-interrupt", 
    # "executor-main", 
    "executor-thread", 
    "task-arena-size-32768"
    ] }



heapless = "0.7"
cortex-m-rt = "0.7"
cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
static_cell = "2.1.0"

defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }
ringbuffer = { version = "0.15.0", default-features = false }
array-concat = "0.5.5"


# [patch.crates-io]
# nrf-softdevice = { git = "https://github.com/embassy-rs/nrf-softdevice.git", rev = "b193eaa1718aeadd3b5eca54f1784aeceba75385" }
# nrf-softdevice-s113 = { git = "https://github.com/embassy-rs/nrf-softdevice.git", rev = "b193eaa1718aeadd3b5eca54f1784aeceba75385" }
